// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface QuadKey$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "QuadKey";
  readonly sourceName: "src/libraries/QuadKey.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c26a95b935bbc40c751424c3e89d67caa7c03d5666377ef66fa7900d8c98e09164736f6c634300081a0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c26a95b935bbc40c751424c3e89d67caa7c03d5666377ef66fa7900d8c98e09164736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/libraries/QuadKey.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["QuadKey"]: QuadKey$Type;
    ["src/libraries/QuadKey.sol:QuadKey"]: QuadKey$Type;
  }
}