// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Erc721Store$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Erc721Store";
  readonly sourceName: "src/contracts/Erc721Store.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/contracts/Erc721Store.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Erc721Store"]: Erc721Store$Type;
    ["src/contracts/Erc721Store.sol:Erc721Store"]: Erc721Store$Type;
  }
}