// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MinimumBid$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MinimumBid";
  readonly sourceName: "src/libraries/MinimumBid.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212206c2003b1e5422edcbbaf94f5be9c8364e4f302f4545aa4fa6bb42401c1ba5dcf64736f6c634300081a0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212206c2003b1e5422edcbbaf94f5be9c8364e4f302f4545aa4fa6bb42401c1ba5dcf64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/libraries/MinimumBid.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MinimumBid"]: MinimumBid$Type;
    ["src/libraries/MinimumBid.sol:MinimumBid"]: MinimumBid$Type;
  }
}