// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MinimumBidFee$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MinimumBidFee";
  readonly sourceName: "src/libraries/MinimumBidFee.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122036e578cfc640e064c618ef6513eeff5c785eb569040655c52391c18d0de5961364736f6c634300081a0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122036e578cfc640e064c618ef6513eeff5c785eb569040655c52391c18d0de5961364736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/libraries/MinimumBidFee.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MinimumBidFee"]: MinimumBidFee$Type;
    ["src/libraries/MinimumBidFee.sol:MinimumBidFee"]: MinimumBidFee$Type;
  }
}