// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IRandomSlots$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IRandomSlots";
  readonly sourceName: "src/interfaces/IRandomSlots.sol";
  readonly abi: [{"inputs":[],"name":"randomSlotCount","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"slot","type":"uint256"}],"name":"randomSlotOdds","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"slot","type":"uint256"}],"name":"randomSlotWeight","outputs":[{"internalType":"int16","name":"","type":"int16"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IRandomSlots.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IRandomSlots"]: IRandomSlots$Type;
    ["src/interfaces/IRandomSlots.sol:IRandomSlots"]: IRandomSlots$Type;
  }
}