import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { test } from 'node:test'

import { normalizeGeneratedImports } from '../normalize-generated-imports.mjs'

test('generated directory namespaces resolve with NodeNext and remain idempotent', () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'typechain-imports-'))
  try {
    fs.mkdirSync(path.join(directory, 'contracts'))
    fs.writeFileSync(path.join(directory, 'contracts/index.ts'), 'export interface Contract {}\n')
    fs.mkdirSync(path.join(directory, 'Internal.sol'))
    fs.writeFileSync(path.join(directory, 'Internal.sol/index.ts'), 'export interface Internal {}\n')
    const source = [
      'import type * as contracts from "./contracts";',
      'import type * as completed from "./contracts/index.js";',
      'import type * as internal from "./Internal.sol";',
      'import type * as ethers from "ethers";',
      'export { Contract__factory } from "./factories/Contract__factory.js";',
      '// import type * as documentation from "./missing";',
      'const example = "import type * as documentation from \'./missing\'";',
    ].join('\n')
    fs.writeFileSync(path.join(directory, 'index.ts'), source)
    assert.equal(normalizeGeneratedImports(directory), 1)
    assert.equal(
      fs.readFileSync(path.join(directory, 'index.ts'), 'utf8'),
      source.replace('from "./contracts"', 'from "./contracts/index.js"')
        .replace('from "./Internal.sol"', 'from "./Internal.sol/index.js"'),
    )
    assert.equal(normalizeGeneratedImports(directory), 0)
  } finally { fs.rmSync(directory, { recursive: true, force: true }) }
})

test('a missing generated directory barrel fails instead of emitting an invalid target', () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'typechain-imports-'))
  try {
    fs.writeFileSync(path.join(directory, 'index.ts'), 'import type * as missing from "./missing";')
    assert.throws(() => normalizeGeneratedImports(directory), /has no index.ts/)
  } finally { fs.rmSync(directory, { recursive: true, force: true }) }
})

test('only the generated legacy TSLint header is removed; examples and ordinary comments remain', () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'typechain-generated-header-'))
  const marker = '/* Autogenerated file. Do not edit manually. */\n'
  const pragma = '/* tslint:disable */\n'
  const body = '/* eslint-disable */\n// ordinary comment\nexport const example = "/* tslint:disable */";\n'
  try {
    const generated = path.join(directory, 'generated.ts')
    const ordinary = path.join(directory, 'ordinary.ts')
    fs.writeFileSync(generated, marker + pragma + body)
    fs.writeFileSync(ordinary, pragma + body)

    assert.equal(normalizeGeneratedImports(directory), 1)
    assert.equal(fs.readFileSync(generated, 'utf8'), marker + body)
    assert.equal(fs.readFileSync(ordinary, 'utf8'), pragma + body)
    assert.equal(normalizeGeneratedImports(directory), 0)
  } finally {
    fs.rmSync(directory, { recursive: true, force: true })
  }
})
