// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DataStore$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DataStore";
  readonly sourceName: "src/contracts/DataStore.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"by","type":"address"},{"indexed":true,"internalType":"uint256","name":"id","type":"uint256"},{"indexed":true,"internalType":"uint256","name":"slot","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"DataSet","type":"event"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/contracts/DataStore.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DataStore"]: DataStore$Type;
    ["src/contracts/DataStore.sol:DataStore"]: DataStore$Type;
  }
}