// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IParentable$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IParentable";
  readonly sourceName: "src/interfaces/IParentable.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"id","type":"uint256"}],"name":"parentOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IParentable.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IParentable"]: IParentable$Type;
    ["src/interfaces/IParentable.sol:IParentable"]: IParentable$Type;
  }
}