// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Erc20Store$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Erc20Store";
  readonly sourceName: "src/contracts/Erc20Store.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"contract IERC20","name":"token","type":"address"}],"name":"_balanceErc20","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/contracts/Erc20Store.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Erc20Store"]: Erc20Store$Type;
    ["src/contracts/Erc20Store.sol:Erc20Store"]: Erc20Store$Type;
  }
}