// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IGeotokenConsumer$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IGeotokenConsumer";
  readonly sourceName: "src/interfaces/IGeotokenConsumer.sol";
  readonly abi: [{"inputs":[],"name":"geotokens","outputs":[{"internalType":"contract IGeotokenErc721","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IGeotokenConsumer.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IGeotokenConsumer"]: IGeotokenConsumer$Type;
    ["src/interfaces/IGeotokenConsumer.sol:IGeotokenConsumer"]: IGeotokenConsumer$Type;
  }
}