// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBurnable$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBurnable";
  readonly sourceName: "src/interfaces/IBurnable.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IBurnable.sol";
  readonly buildInfoId: "solc-0_8_26-873bbef1a0340d91b318c0a2842afb70a7679095";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBurnable"]: IBurnable$Type;
    ["src/interfaces/IBurnable.sol:IBurnable"]: IBurnable$Type;
  }
}